version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /cpg-rs
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /oxidized
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /astgen-rs/abap2cpg
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /astgen-rs/csharpsrc2cpg
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /astgen-rs/javasrc2cpg
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /astgen-rs/jimple2cpg
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /astgen-rs/kotlin2cpg
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /astgen-rs/php2cpg
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]
  - package-ecosystem: cargo
    directory: /astgen-rs/swiftsrc2cpg
    schedule:
      interval: weekly
    groups:
      rust-dependencies:
        patterns: ["*"]
