import com.typesafe.sbt.packager.Keys.stagingDirectory

import scala.sys.process.Process

name := "pysrc2cpg"

// Differential reference (rust/crates/pyastgen-cli/tests/differential_json.rs,
// gated on PYASTGEN_REFERENCE): pysrc2cpg's production parser is the *in-tree*
// JavaCC grammar generated by `javaCCTask` below (pythonGrammar.jj ->
// io.joern.pythonparser) and driven from the JVM via PyAstGenRunner.scala. It is
// library code, NOT a standalone binary or a published release artifact, so
// there is no download task to add. The differential test therefore self-skips
// unless PYASTGEN_REFERENCE points at a CLI honouring `-out <dir> <input>` (for
// example a previously built `pyastgen` revision).

lazy val PyAstgenWin      = "pyastgen-win.exe"
lazy val PyAstgenWinArm   = "pyastgen-win-arm.exe"
lazy val PyAstgenLinux    = "pyastgen-linux"
lazy val PyAstgenLinuxArm = "pyastgen-linux-arm"
lazy val PyAstgenMac      = "pyastgen-macos"
lazy val PyAstgenMacArm   = "pyastgen-macos-arm"

dependsOn(
  Projects.dataflowengineoss  % "test->test",
  Projects.x2cpg              % "compile->compile;test->test",
  Projects.linterRules % ScalafixConfig
)

libraryDependencies ++= Seq(
  "io.shiftleft"           %% "codepropertygraph"          % Versions.cpg,
  "org.scala-lang.modules" %% "scala-parallel-collections" % Versions.scalaParallel,
  "com.lihaoyi"            %% "ujson"                      % Versions.upickle,
  "org.scalatest"          %% "scalatest"                  % Versions.scalatest % Test
)

enablePlugins(JavaAppPackaging, LauncherJarPlugin)
trapExit                      := false
Global / onChangedBuildSource := ReloadOnSourceChanges

val javaCCTask = taskKey[Seq[File]]("Generate compiler code with JavaCC")
javaCCTask / fileInputs += baseDirectory.value.toGlob / "pythonGrammar.jj"
javaCCTask := {
  import org.javacc.parser.{Main => JavaCCMain}
  val outputDir       = (Compile / sourceManaged).value / "io" / "joern" / "pythonparser"
  val inputFileOption = javaCCTask.inputFiles.head
  if (
    !outputDir.exists() ||
    javaCCTask.inputFileChanges.created.nonEmpty ||
    javaCCTask.inputFileChanges.modified.nonEmpty
  ) JavaCCMain.mainProgram(Array(s"-OUTPUT_DIRECTORY=$outputDir", inputFileOption.toString))
  os.walk(os.Path(outputDir)).filter(path => os.isFile(path) && path.ext == "java").map(_.toIO)
}

Compile / sourceGenerators += javaCCTask

lazy val pyAstGenCurrentBinaryName = taskKey[String]("pyastgen binary name for the current host")
pyAstGenCurrentBinaryName := {
  (Environment.operatingSystem, Environment.architecture) match {
    case (Environment.OperatingSystemType.Windows, Environment.ArchitectureType.X86)   => PyAstgenWin
    case (Environment.OperatingSystemType.Windows, Environment.ArchitectureType.ARMv8) => PyAstgenWinArm
    case (Environment.OperatingSystemType.Linux, Environment.ArchitectureType.X86)   => PyAstgenLinux
    case (Environment.OperatingSystemType.Linux, Environment.ArchitectureType.ARMv8) => PyAstgenLinuxArm
    case (Environment.OperatingSystemType.Mac, Environment.ArchitectureType.X86)     => PyAstgenMac
    case (Environment.OperatingSystemType.Mac, Environment.ArchitectureType.ARMv8)   => PyAstgenMacArm
    case _                                                                           => PyAstgenLinux
  }
}

lazy val pyAstGenBuildRust = taskKey[File]("Build local Rust pyastgen and install it under bin/astgen")
pyAstGenBuildRust := {
  val rustRoot = baseDirectory.value / "rust"
  val localBinaryName =
    if (Environment.operatingSystem == Environment.OperatingSystemType.Windows) "pyastgen.exe" else "pyastgen"
  val exitCode = Process(Seq("cargo", "build", "--release", "--bin", "pyastgen"), rustRoot).!
  if (exitCode != 0) {
    sys.error(s"cargo build failed with exit code $exitCode")
  }

  val builtBinary = rustRoot / "target" / "release" / localBinaryName
  val astGenDir   = baseDirectory.value / "bin" / "astgen"
  val targetFile  = astGenDir / pyAstGenCurrentBinaryName.value
  astGenDir.mkdirs()
  IO.copyFile(builtBinary, targetFile, preserveLastModified = true)
  targetFile.setExecutable(true, false)

  val distDir = (Universal / stagingDirectory).value / "bin" / "astgen"
  distDir.mkdirs()
  IO.copyDirectory(astGenDir, distDir, preserveExecutable = true)

  streams.value.log.info(s"installed Rust pyastgen to $targetFile")
  targetFile
}

Compile / compile := ((Compile / compile) dependsOn pyAstGenBuildRust).value
