[package]
name = "pyastgen"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "pyastgen"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
ignore.workspace = true
pyastgen-core = { path = "../pyastgen-core" }
regex.workspace = true

[dev-dependencies]
assert_cmd = "2"
serde_json.workspace = true
tempfile.workspace = true
