[workspace]
members = [
  "crates/swiftastgen-cli",
  "crates/swiftastgen-core",
]
resolver = "2"

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.4.2"

[workspace.dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
ignore = "0.4"
regex = "1"
serde_json = { version = "1", features = ["preserve_order"] }
tempfile = "3"
tree-sitter = "0.26"
tree-sitter-swift = "0.7"
