[package]
name = "swiftastgen-cli"
edition.workspace = true
license.workspace = true
version.workspace = true

[[bin]]
name = "SwiftAstGen"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
ignore.workspace = true
regex.workspace = true
swiftastgen-core = { path = "../swiftastgen-core" }

[dev-dependencies]
assert_cmd = "2"
serde_json.workspace = true
tempfile.workspace = true
