[package]
name = "cpg-incremental"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cpg-core.workspace = true
cpg-frontend.workspace = true
cpg-analysis.workspace = true
rayon.workspace = true

[dev-dependencies]
cpg-lang-c.workspace = true
cpg-lang-python.workspace = true
cpg-lang-ts.workspace = true
