package io.joern.x2cpg.frontendspecific.pysrc2cpg

/** Return type stubs for Python standard library builtins and commonly used functions.
  * Used by PythonTypeRecovery to infer return types when no source code is available.
  */
object PythonTypeStubs {

  private val b = Constants.builtinPrefix

  private val stubReturnTypes: Map[String, String] = Map(
    // Builtin functions
    s"${b}len"        -> s"${b}int",
    s"${b}int"        -> s"${b}int",
    s"${b}str"        -> s"${b}str",
    s"${b}float"      -> s"${b}float",
    s"${b}bool"       -> s"${b}bool",
    s"${b}bytes"      -> s"${b}bytes",
    s"${b}list"       -> s"${b}list",
    s"${b}dict"       -> s"${b}dict",
    s"${b}set"        -> s"${b}set",
    s"${b}tuple"      -> s"${b}tuple",
    s"${b}type"       -> s"${b}type",
    s"${b}repr"       -> s"${b}str",
    s"${b}abs"        -> s"${b}int",
    s"${b}hash"       -> s"${b}int",
    s"${b}id"         -> s"${b}int",
    s"${b}ord"        -> s"${b}int",
    s"${b}chr"        -> s"${b}str",
    s"${b}hex"        -> s"${b}str",
    s"${b}oct"        -> s"${b}str",
    s"${b}bin"        -> s"${b}str",
    s"${b}range"      -> s"${b}range",
    s"${b}enumerate"  -> s"${b}enumerate",
    s"${b}zip"        -> s"${b}zip",
    s"${b}map"        -> s"${b}map",
    s"${b}filter"     -> s"${b}filter",
    s"${b}sorted"     -> s"${b}list",
    s"${b}reversed"   -> s"${b}reversed",
    s"${b}isinstance" -> s"${b}bool",
    s"${b}issubclass" -> s"${b}bool",
    s"${b}hasattr"    -> s"${b}bool",
    s"${b}getattr"    -> s"${b}object",
    s"${b}callable"   -> s"${b}bool",
    s"${b}max"        -> s"${b}object",
    s"${b}min"        -> s"${b}object",
    s"${b}sum"        -> s"${b}int",
    s"${b}round"      -> s"${b}int",
    s"${b}input"      -> s"${b}str",
    s"${b}open"       -> "io.TextIOWrapper",
    s"${b}format"     -> s"${b}str",
    // Short names (for unresolved imports)
    "len"        -> s"${b}int",
    "int"        -> s"${b}int",
    "str"        -> s"${b}str",
    "float"      -> s"${b}float",
    "bool"       -> s"${b}bool",
    "bytes"      -> s"${b}bytes",
    "list"       -> s"${b}list",
    "dict"       -> s"${b}dict",
    "set"        -> s"${b}set",
    "tuple"      -> s"${b}tuple",
    "type"       -> s"${b}type",
    "repr"       -> s"${b}str",
    "abs"        -> s"${b}int",
    "hash"       -> s"${b}int",
    "id"         -> s"${b}int",
    "ord"        -> s"${b}int",
    "chr"        -> s"${b}str",
    "hex"        -> s"${b}str",
    "oct"        -> s"${b}str",
    "bin"        -> s"${b}str",
    "range"      -> s"${b}range",
    "enumerate"  -> s"${b}enumerate",
    "zip"        -> s"${b}zip",
    "map"        -> s"${b}map",
    "filter"     -> s"${b}filter",
    "sorted"     -> s"${b}list",
    "reversed"   -> s"${b}reversed",
    "isinstance" -> s"${b}bool",
    "issubclass" -> s"${b}bool",
    "hasattr"    -> s"${b}bool",
    "callable"   -> s"${b}bool",
    "max"        -> s"${b}object",
    "min"        -> s"${b}object",
    "sum"        -> s"${b}int",
    "round"      -> s"${b}int",
    "input"      -> s"${b}str",
    "open"       -> "io.TextIOWrapper",
    "format"     -> s"${b}str",
    // Common stdlib
    "os.path.join"      -> s"${b}str",
    "os.path.exists"    -> s"${b}bool",
    "os.path.isfile"    -> s"${b}bool",
    "os.path.isdir"     -> s"${b}bool",
    "os.path.basename"  -> s"${b}str",
    "os.path.dirname"   -> s"${b}str",
    "os.path.abspath"   -> s"${b}str",
    "os.path.splitext"  -> s"${b}tuple",
    "os.getcwd"         -> s"${b}str",
    "os.listdir"        -> s"${b}list",
    "json.loads"        -> s"${b}dict",
    "json.dumps"        -> s"${b}str",
    "json.load"         -> s"${b}dict",
    "json.dump"         -> s"${b}None",
    // os / environment (taint sources)
    "os.getenv"         -> s"${b}str",
    "os.environ.get"    -> s"${b}str",
    "os.urandom"        -> s"${b}bytes",
    "os.makedirs"       -> s"${b}None",
    "os.mkdir"          -> s"${b}None",
    "os.remove"         -> s"${b}None",
    "os.rename"         -> s"${b}None",
    // process execution (command-injection sinks)
    "os.system"             -> s"${b}int",
    "os.popen"              -> "os._wrap_close",
    "subprocess.run"        -> "subprocess.CompletedProcess",
    "subprocess.call"       -> s"${b}int",
    "subprocess.check_call" -> s"${b}int",
    "subprocess.check_output" -> s"${b}bytes",
    "subprocess.Popen"      -> "subprocess.Popen",
    // serialization (deserialization sinks)
    "pickle.loads"      -> s"${b}object",
    "pickle.load"       -> s"${b}object",
    "pickle.dumps"      -> s"${b}bytes",
    "yaml.load"         -> s"${b}object",
    "yaml.safe_load"    -> s"${b}object",
    "yaml.dump"         -> s"${b}str",
    "marshal.loads"     -> s"${b}object",
    // encoding / hashing
    "base64.b64encode"  -> s"${b}bytes",
    "base64.b64decode"  -> s"${b}bytes",
    "base64.urlsafe_b64decode" -> s"${b}bytes",
    "hashlib.md5"       -> "hashlib._Hash",
    "hashlib.sha1"      -> "hashlib._Hash",
    "hashlib.sha256"    -> "hashlib._Hash",
    "hashlib.new"       -> "hashlib._Hash",
    // regular expressions
    "re.compile"        -> "re.Pattern",
    "re.match"          -> "re.Match",
    "re.search"         -> "re.Match",
    "re.fullmatch"      -> "re.Match",
    "re.findall"        -> s"${b}list",
    "re.finditer"       -> s"${b}iterator",
    "re.sub"            -> s"${b}str",
    "re.split"          -> s"${b}list",
    "re.escape"         -> s"${b}str",
    // databases (SQL-injection sinks)
    "sqlite3.connect"   -> "sqlite3.Connection",
    // networking / URLs (SSRF sources & sinks)
    "urllib.parse.urlparse"  -> "urllib.parse.ParseResult",
    "urllib.parse.parse_qs"  -> s"${b}dict",
    "urllib.parse.quote"     -> s"${b}str",
    "urllib.parse.unquote"   -> s"${b}str",
    "urllib.parse.urlencode" -> s"${b}str",
    "urllib.request.urlopen" -> "http.client.HTTPResponse",
    "socket.socket"          -> "socket.socket",
    "socket.gethostname"     -> s"${b}str",
    // requests (third-party HTTP)
    "requests.get"      -> "requests.Response",
    "requests.post"     -> "requests.Response",
    "requests.put"      -> "requests.Response",
    "requests.delete"   -> "requests.Response",
    "requests.patch"    -> "requests.Response",
    "requests.head"     -> "requests.Response",
    "requests.request"  -> "requests.Response",
    "requests.Session"  -> "requests.Session",
    // misc stdlib
    "time.time"         -> s"${b}float",
    "time.sleep"        -> s"${b}None",
    "random.random"     -> s"${b}float",
    "random.randint"    -> s"${b}int",
    "random.choice"     -> s"${b}object",
    "math.sqrt"         -> s"${b}float",
    "math.floor"        -> s"${b}int",
    "math.ceil"         -> s"${b}int",
    "math.pow"          -> s"${b}float",
    "uuid.uuid4"        -> "uuid.UUID",
    "tempfile.mkdtemp"  -> s"${b}str",
    "tempfile.mkstemp"  -> s"${b}tuple",
    "shutil.copy"       -> s"${b}str",
    "shutil.move"       -> s"${b}str",
    "collections.OrderedDict" -> s"${b}dict",
    "collections.defaultdict" -> s"${b}dict",
    "collections.Counter"     -> "collections.Counter"
  )

  def returnTypeFor(name: String): Option[String] = stubReturnTypes.get(name)
}
